### PR TITLE
WIP: one terminal per workspace

### PR DESCRIPTION
**Pull request by freimair**
Just coded up a "one terminal per workspace" feature.

added a few fixes as well.

I am going to live with my results for a few days and see if any issues arise.

Will create new PRs for logical parts of this PR:
- [x] addressing focus behavior: https://github.com/diegodario88/quake-terminal/pull/10
- [x] increase felt performance: https://github.com/diegodario88/quake-terminal/pull/17
- [x] general improvements: https://github.com/diegodario88/quake-terminal/pull/16
- [ ] terminal per workspace: TBD

### CODE REVIEW

**Comment by freimair** [comment]
@diegodario88 I am quite happy with the feature using Wayland - everything works as expected.

However, X11 does some very inconvenient stuff:
- attaching listeners to the wrong windows
- hide/show actions are performed on the wrong windows
- even QuakeMode class instances seem to arbitrarily get mixed up

do you have any insights on what is going on?

**Comment by diegodario88** [comment]
Hi @freimar,

I'm glad to hear that you're enjoying it on Wayland! However, I'm sorry to hear that you're experiencing these issues with X11. It's not always easy to pinpoint the exact cause of such problems, and without more specific information, it's challenging for me to provide any insights. Additionally, it's worth noting that X11 is gradually being deprecated in favor of Wayland, which means that efforts to address these issues on X11 might be limited.

**Comment by diegodario88** [comment]
Hello @freimair, just wanted to inform you that I'm closing this as the mentioned feature is beyond the scope of this project. Achieving better results might be possible using a [terminal multiplexer](https://en.wikipedia.org/wiki/Terminal_multiplexer).

**Comment by freimair** [comment]
@diegodario88 well no, actually, I do not think that a terminal multiplexer is a valid alternative.

consider this (my) use case:
- having to put out fires on different projects all day long
- one project, one workspace
- switch to the workspace with the target project
- hit [Hotkey] and get the terminal window as a dropdown
- at the directory one has configured hours back including history and
- with terminator, possibly even a set of terminals specific for this project (ssh, diffs, general purpose shell, git, ...)

without the need to sift through another terminal multiplexer again.

gnome workspaces are designed that way. why lock the terminal dropdown to kind-of "always on visible workspace" setting?

besides, I started with Guake, went over to quake-terminal and now to your rewrite. All of them eventually had the request to make terminals per workspace a feature.


that being said, sorry that there have been no news here, I am just testing if I can finally use Wayland because the much-needed screen-sharing feature hardly worked w/o x11 as a backend...

**Pull request closed without merging**
